#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
KBUILD_CFLAGS := -fno-builtin -Werror -Iboard/$(BOARDDIR)/../common/include

obj-y	:= nt72671_a32_tk.o
obj-$(CONFIG_NVTTK_EBURNER_V2) += nvt_panel_init.o
