#
# (C) Copyright 2000-2010
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= lowlevel_init.o
obj-y	+= soc.o
obj-y	+= clock.o
obj-y	+= crypto.o
obj-y	+= nt96680_serial.o
obj-y	+= nvt-otp.o
