obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_ecc_layouts.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_globals.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_gpio.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_io.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_ir.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_kapi.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_mtd.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_nfc.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_init.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_parts.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_utils.o
obj-$(CONFIG_NVT_NAND_FLASH_CONTROLLER) += nt72_nand_uboot.o

